### ISSUE TITLE
Robot simulators to validate code without Robot

### ISSUE THREAD

**Issue by dotnetprofessional** [SaintsRobotics/frc2020#2]
### Criteria

* What are the available options?
* What are the pros/cons of each option?
* Ease of use of each option?
* Are the options compatible with FRC 2020 season?

**Comment by lachlanmcglennon** [comment]
snobot sim features
Simple physics based motor simulations
Feedback Sensor simulation (AnalogIO, DigitalIO, Encoders, Gyros)
NavX Simulation for the 3-axis Gyro and 3-axis Accelerometers
CTRE CanTalon and Pigeon IMU simulations. Due to the incredble power of this speed control, I cannot guarantee that all features will work, even if they appear to. It covers most of the control modes, but without something to test against your mileage might vary.
Open to extension for custom I2C, SPI, Potentiometer, Motors servo'd by limit switches, etc. Hopefully anything you need!

**Comment by lachlanmcglennon** [comment]
do you think swerve is supported?
it can simulate motors and switches and encoders there are minimal graphics

**Comment by lachlanmcglennon** [comment]
it does not look easy to use

**Comment by DarthAV** [comment]
Based on [this](https://www.reddit.com/r/FRC/comments/8ep4sn/synthesis_frc_simulator/dxxyytd/?utm_source=BD&utm_medium=Search&utm_name=Bing&utm_content=PSR1)  Reddit thread

> "The robot driving function is decent, but only if you use a robot that has dropped-center tank drive. Mecanum, **Swerve**, and Omni are too complicated, and it just doesn’t work."

Synthesis has limited support for Swerve Wheels which is obviously integral to our robots.

**Comment by DarthAV** [comment]
sorry

**Comment by dotnetprofessional** [comment]
Seems new 2020 version of SnobotSim is out:

https://www.chiefdelphi.com/t/snobotsim-2020/372251
